num_wheels: 4

device: enp2s0

wheel0:
  ethercat_number: 2
  x: 0.175
  y: 0.1605
  a: -2.50

wheel1:
  ethercat_number: 3
  x: -0.175
  y: 0.1605
  a: -1.25

wheel2:
  ethercat_number: 5
  x: -0.175
  y: -0.1607
  a: -2.14

wheel3:
  ethercat_number: 6
  x: 0.175
  y: -0.1605
  a: 1.49

